---
title: "Multivariate Data Analysis mit R"
author: 
  - name: "Dr. Uwe Remer"
    affiliation: "Universität Stuttgart"
    email: "uwe.remer@sowi.uni-stuttgart.de"
date: "WS 2020/2021"
output:
  html_document:
    toc: yes
    number_sections: no
    toc_depth: 3
    toc_float:
      collapsed: true
    df_print: paged
    highlight: tango
    theme: spacelab
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 2
    keep_tex: yes
subtitle: (und etwas SPSS)
geometry: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




# Detailplanung

## S1 - Konstituierende Sitzung 

02.11.2020

### Beschreibung 
In der ersten Sitzung erhalten Sie im ersten Teil einige allgemeine Informationen zu R, seinem Ökosystem (Pakete, Community) und darüber, warum R die richtige Wahl ist, wenn Sie sich entscheiden müssen, ein Statistikprogramm zulernen. Dabei gehe ich im besonderen auf die Unterschiede zwischen R und SPSS ein.  
Im zweiten Teil erfahren Sie, was das Konzept der Objektorientierung ist und erhalten einen Überblick über grundlegende Datentypen in R und wie man sie indiziert.  
Der dritte Teil dreht sich dann um Ablauf und Formalia des Seminars.

- Teil 1: Vorstellung R
  - Welche Gründe sprechen für R? 
  - Das R ökosystem
  - Vergleich R vs. SPSS
- Teil 2: Die R Ontologie
  - Objetkorientierung
  - Datentypen und Indizierung
- Teil 3 - Seminarvorstellung: 
  - Ziele und Erwartungen
  - Inhalte und Ablauf
  - Formalia

### Lernziele 
- Die Studierenden können die grundsätzlichen Unterschiede zwischen R und SPSS benennen.
- Die Studierenden können erläutern, was das Konzept der Objektorientierung bedeutet.
- Die Studierenden erkennen unterschiedliche Datentypen und können deren Merkmale benennen.
- Die Studierenden wissen, wie unterschiedliche Datentypen indiziert werden. 

### Didaktik
- Teil 1 und 2 als Vortragsaufzeichnung  
- Teil 3 als live Webex Meeting mit Präsentation


### ToDo und Notizen:


R Ökosystem

NEU: Was unterscheidet R von SPSS

- gui vs. komandozeile
- Syntax vs. Programiersprache
- Datensatz vs. Objekte
- proprietere Lizenz vs. freie Software
- Daten, Input, Output, vs. 



Objektorientierung

Sie erinnern sich an letzte Woche: R ist eine objektorientierte Programmiersprache. 
Was heißt das? Vereinfacht kann man sagen, dass alles
Alles in R ist ein Objekt. 
Jedes Objekt gehört zu einer Klasse und mit jeder Klasse sind bestimmte
Methoden (Funktionen) verbunden. 
Was bedeutet das?

Beispiel: die Zahlenreihe 2,4,6,8 kann ich als Objekt in R speichern
Reihe <- c(1,2,3,4)
Das Objekt „Reihe“ gehört dann zur Klasse numerischer Vektor. Diese Klasse gibt vor, welche Funktionen damit erlaubt sind. 
Wenn das Objekt zum Beispiel eine Vektor aus Wörtern wäre, dann wären andere Funktionen zulässig. Hier kein addieren möglich, kein Mittelwert berechnen etc. 
Die Funktionen selbst sind auch wieder Objekte. 
Das ermöglicht, dass zum Beispiel eine Funktion wie plot() immer weiß, was grafisch ausgegeben werden soll, je nach Klasse der Objekte, auf die die Funktion angewendet wird.

Aber fangen wir von Grund auf an.


## S2 - Erste Schritte mit R  
**09.11.2020**

### Beschreibung 

Die zweite Sitzung stellt die R Kommandozeile ("Console") vor und demonstriert erste einfache Operationen ("R als Taschenrechner"). Dann lernen Sie R-Studio als GUI (Grafical User Interface) kennen, das die Bedienung erleichtert. Wir werden dann praktische Erfahrung mit den bereits in Sitzung 1 kennengelernten Datentypen und den Möglichkeiten der Indizierung sammeln. Schauen Wir schauen auf typische Fehler und wie man diese beheben kann. Abschließend programmieren wir unsere erste eigene Funktion.


### Lernziele 
- Die Studierenden wissen, wie man Befehle mit der R Kommandozeile und über R Scripte ausführt.
- Die Studierenden finden sich in der R-Studio GUI zurecht.
- Die Studierenden können Objekte unterschiedlicher Datentypen erstellen, aufrufen, verändern und erste Funktionen darauf anwenden.
- Die Studierenden können erste Fehlermeldungen und Probleme verstehen und lösen:
  - Syntaxfehler verhindern, dass der Code ausgeführt wird (unvollständige Befehle, Klammerfehler)
  - Laufzeitfehler lassen die Ausführung abbrechen ( unterschiedliche Längen von Objekten. teilen durch 0, falsche Datentypen)
  - Abgrenzung zu logische Fehler: Code läuft, liefert aber falsche Ergebnisse
- Die Studierenden kennen das Konzept einer Funktion und können einfache Funktionen erstellen. 


### Literatur

Kabacoff 2011: 73-116

### Didaktik

#### Einführungsvideo

- Wiederholung 
  - Objektorientierung
  - Datentypen und Indizierung
- R Kommandozeile und Taschenrechner
- R-Studio GUI

#### ILIAS html Lernmodul(aus R Markdown html)

- Datentypen erstellen, abrufen, verändern
- Datentypen erkennen und Struktur erkunden
- Funktionen nutzen
- Erste Funktion erstellen (Mittelwert)

#### Ergebnissicherung LearnR Tutorial

#### TODO: Video zu Fehlermeldungen

- Präsentationsaufzeichnung
- R Session Aufzeichnung
- Ergebnissicherung LearnR Tutorial -> 
  - Pakage Datensatz selbst ertsellen statt parlgov
  - Datenstruktur der Aufgabe 2_Wiederholungsaufgabe ändern zu zeilen parteien, spalten wahlen


### ToDo und Notizen:

Hinweis geben, dass in Zukunft nur mit Rstuio gearbeitet wird. Man die reine R Kommandozeile nicht aufrufen muss.

- Datenstrukturen stat Datentypen
- WICHTIG: NAMES Objekte ergänzen!
- FUNKTIONEN Slides ergänzen
- Video zu Fehlermeldungen
- Ergebnissicherung LearnR Tutorial




## S3 - R Workflow 
**16.11.2020**

### Beschreibung 


### Lernziele

- Daten einlesen
- Daten und Code handling (R Projekte, Workingdirectory, Ordnerstruktur) 
- Code schreiben (Variablenanme, Einrückungen, Kommentare etc.)
- R Markdown  

### Didaktik

ILIAS Lernmodul
Begrüßungsvideo
Inhaltsseite Funktionen 
Inhaltsseite -> Wiederholung via LearnR

Überleitungsvideo: Jetzt data.frame als neue Datenstruktur
"Finden Sie heraus, wo ihr Datensatz ist" --> Später: Projekt.
Skript / Learnr: Einlesen 
LearnR Arbeiten mit Dataframes

kbacoff pretty -> table

Kein überspeichern des DAetnsatzes. Nur speichern des Skriptes.

Überleitungsvideo: R Workflow





### ToDo und Notizen:

data.frame
Factors

head()
tails()

Kabacoff S12 Functions to handle workspace


Einrücken, verschachteln etc.







##  S4 - Recodieren, transformieren, Indices
**23.11.2020**

### Beschreibung 

In vielen Fälen können die Variablen, wie sie in einem Datensatz vorliegen, nicht direkt für eine Analyse genutzt werden. Oft müssen fehlende Werte definiert (zumindest geprüft werden), es müssen Merkmalsausprägungen umkodiert werden, oder es müssen mehrere Variablen zusammengefasst werden, um komplexere Konstrukte angemessen zu erfassen. Diese Sitzung beschäftigt sich mit diesen typischen Schritten der Datenvorbereitung, die im Zuge der *Operationalisierung* durchgeführtwerden: recodieren, transformieren und Indexbildung. 

### Lernziele

- Missing Values erkennen und definieren
- Variablen recodieren (einzelne Werte oder ganze Variablen)

### Didaktik

- Missing Values
    - prüfen
    - definieren
    - zählen
    - Subset für Datensatz ohne `NA`s erstellen
- Recode
    - einzelne Werte einer `character` Variable ändern
    - Recode einer ganzen Variable mit dem `car`-package
    - Faktor-Variable erstellen
- Transformieren (Beispiele)
    - Variable drehen
    - z-Transformation
    - logarithmieren
- Indexbildung
    - Einfacher Additiver Index 
    - komplexerer Index




### ToDo und Notizen

Aufgabe 3:
Erstellen Sie einen formativen Index `SERL` *Socioeconomic Ressource Level* 

Missing Values
    - prüfen
    - definieren
    - zählen
    - Subset für Datensatz ohne `NA`s erstellen



### Aufgabe B

Lesen Sie den ESS als SPSS-Datei ein. Nutzen Sie die Länderkürzel der Variable `cntry` um einen Vektor der Osteuropäischen EU-Länder zu erstellen. Nutzen Sie diesen dann mit dem `%in%` Operator, um je einen Osteuropa und Westeurop Subset des Datensatzes zu erstellen. Schließen Sie die Schweiz und Montenegro dabei als nicht-EU Länder aus. 

1. Suchen Sie im Datensatz nach *einer* Variable, mit der Sie politisches Vertrauen messen würden.
2. Berechnen Sie damit das durchschnittliche politische Vertrauen je für westeuropäischen und für die osteuropäischen Länder.
3. Erstellen Sie eine relative Häufigkeitstabelle für die Variable `vote`. 
4. Vergleichen Sie dann, wie hoch der Anteil der Wähler unter den Befragten ist, die überdi





## Sitzung 5 - Wiederholung: uni- und bivariate Statistik 
**30.11.2020** 

## 07.12.2020 Sitzung 6 - Mittelwertvergleich (t-Test) {.unlisted .unnumbered}
## 14.12.2020 Sitzung 7 - Varianzanalyse (ANOVA) {.unlisted .unnumbered}
## 21.12.2020 Sitzung 8 - Explorative Faktorenanalyse und Reliabilität {.unlisted .unnumbered}
## 11.01.2021 Sitzung 9 - Regressionsanalyse I, Einführung (bivariater Fall) {.unlisted .unnumbered}
## 18.01.2021 Sitzung 10 - Regressionsanalyse II, multivariate Regression {.unlisted .unnumbered}
## 25.01.2021 Sitzung 11 - Regressionsanalyse III, Kausalität und Drittvariablenkontrolle {.unlisted .unnumbered}
## 01.02.2021 Sitzung 12 - Regressionsanalyse IV, Regressionsannahmen und -diagnostik {.unlisted .unnumbered}
## 08.02.2021 Sitzung 13 - Regressionsanalyse V, Moderator- und Mediator-Effekte {.unlisted .unnumbered}


## Sitzung Hausarbeit: 

Aufbau
Was gehört rein:

Zusammenfassung: Was macht das Skript?

Abschnitte mit Überschriften Strukturieren 
Daten einlesen
Variablen Vorbereiten
Bivariate Analysen
Regressionsanalysen
Robustheits-Checks

Einzelne Schritte beschreiben:
Was tun Sie, wie und warum?
Beschreibung ist so aussagekräftig, dass man auch ohne Code zum selben ergebnis käme

Wenn entscheidungen getroffen werden (müssen): Hier kann man dokumentieren!
In der Arbeit schreibt man: "xyz wurde geprüft..." Im Anhang wird diese Prüfung dann berichtet. Z.B: alternative Operationalisierungen. 


GGf. Einzelne Codezeilen zusätzlich kommentieren, wenn nicht
direkt ersichtlich ist, was hier passiert.
